
volumes:
    mysql_data:
    redis_data:





services:
    mysql:
        image: mysql:8
        ports:
            #coenctar mi puerto local 3306 al puerto 3306 el contenedor
            #Opcion 1 es lo siguiente
            #- 3306:3306
            - published: ${DEMO_MYSQL_POTT:-3306}
              target: 3306
        volumes:
            #Montar el volumen o directorio de mysql_data en el contenedor esto es para guardar datos de la BD
            #se pueden utilizar variables de ambiente que esten en un archivo de .env
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL:USER: demo
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: demo_development
            MYSQL_ROOT_PASSWORD: admin


    redis:
        image: redis:6-alpine
        ports:
            #coenctar mi puerto local 3306 al puerto 3306 el contenedor
            #Opcion 1 es lo siguiente
            #- 3306:3306
            - published: ${DEMO_REDIS_POTT:-6379}
              target: 6379
        volumes:
            #Montar el volumen o directorio de mysql_data en el contenedor esto es para guardar datos de la BD
            #se pueden utilizar variables de ambiente que esten en un archivo de .env
            - redis_data:/data

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - published: ${DEMO_MAILHOG_POTT:-8025}
              target: 8025